version: "3.8"
services: 
  python3.9:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/root/
    working_dir: /root/
    tty: true
    #コマンドネットワーク作成$docker network create shared-network
    networks:
      - default
      - shared-network

    
networks:
  shared-network:
    external: true